# LivingWorkspace
name: LivingWorkspace
author: Rodrigo Cancino (Coto)

# ---- Main settings ----
title: Living Workspace
description: >- # this means to ignore newlines until "baseurl:"
  Your Private, Safe & Comfortable Workspace in Buenos Aires.
  Enjoy uninterrupted work with privacy, safety, and comfort.

  Perfect for freelancers, students, remote workers, startups, 
  and small business owners.
keywords: "coworking, Buenos Aires, remote work, freelancers, startups, students, private office, safety, comfort"
slogan: "Workspace with Privacy, Security and Comfort."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://livingworkspace.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "https://livingworkspace.github.io/assets/img/logo.png"
color_main: "#091C99"
google_analytics: "G-7SS07FXHTW"

# ---- Secondary settings ----
twitter_username: LivingWorkspace

# ---- Jekyll settings ----
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-timeago

permalink: /:categories/:title/
#permalink: /:categories/:year/:month/:day/:title:output_ext

jekyll_timeago:
  depth: 2
  translations_path: '/_18n/*.yml'
  default_locale: 'pt'
  fallbacks: true
  available_locales:
    - 'en'
    - 'es'
    - 'pt'

# jekyll-multiple-languages-plugin settings
languages: ["pt", "en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]



# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
