# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Living Workspace
name: LivingWorkspace
description: >- # this means to ignore newlines until "baseurl:"
  Your Private, Safe & Comfortable Workspace in Buenos Aires.
  Enjoy uninterrupted work with privacy, safety, and comfort.

  Perfect for freelancers, students, remote workers, startups, and small business owners.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://livingworkspace.github.io" # the base hostname & protocol for your site, e.g. http://example.com
slogan: "Privacy, Security and Comfort."
keywords: "coworking, Buenos Aires, remote work, freelancers, startups, students, private office, safety, comfort"
logo: "https://livingworkspace.github.io/assets/logo-black.png"

# Site Settings
twitter_username: LivingWorkspace
google_analytics: "G-7SS07FXHTW"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-timeago

permalink: /:categories/:title/
#permalink: /:categories/:year/:month/:day/:title:output_ext

jekyll_timeago:
  depth: 2
  translations_path: '/_18n/*.yml'
  default_locale: 'pt'
  fallbacks: true
  available_locales:
    - 'en'
    - 'es'
    - 'pt'

# jekyll-multiple-languages-plugin settings:
languages: ["pt", "en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
